### ISSUE TITLE
Property 'parameters' on Entity 'GAIHit' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

### ISSUE THREAD

**Issue by mohamadakmalshukri** [mkudrnac/google_analytics_legacy#2]
[error] fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.

CoreData: fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.

2022-04-26 09:28:25.848451+0800 Runner[1533:555834] [error] CoreData: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.

CoreData: warning: Property 'parameters' on Entity 'GAIHit' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

**Comment by mohamadakmalshukri** [comment]
i got this error while running on iOS ..

**Comment by miroslavbaudys** [comment]
Hi, this is problem with google analytics SDK. I cannot do anything with it, you have to wait for google to fix SDK or use firebase SDK.

https://developers.google.com/analytics/devguides/collection/ios/changelog

**Comment by ruiq** [comment]
update google analytics SDK version（ in .podspec) to 3.20  can solve this problem。

**Comment by miroslavbaudys** [comment]
> update google analytics SDK version（ in .podspec) to 3.20 can solve this problem。

Thank you, I will publish new version
