### ISSUE TITLE
Event parameter strings are encoded in iOS

### ISSUE THREAD

**Issue by Ashish6295** [mkudrnac/google_analytics_legacy#3]
When ever an event is fired from iOS app
spaces are replaced with %20
this happens with //, : etc (some kind of encoding is happening)

This affects only iOS 
![Screenshot 2022-06-27 142130](https://user-images.githubusercontent.com/51740841/175899765-0a3b8fca-ece7-4966-893d-4262e2fec336.png)

e.g Data%20Connection%20Switch%20Accessed

**Comment by miroslavbaudys** [comment]
Hi, can you please attach example code? Thank you

**Comment by Ashish6295** [comment]
> Hi, can you please attach example code? Thank you

`if(isGoogleAnalytics360EnabledForAHA){
        var eventAction = widget.guideline!.children!.getNameForChapterNumber(widget.pageSession)! + '_External link clicked';
        await sendEventToGoogleAnalyticsLegacy.sendEventsToGoogleAnalyticsLegacy(
            eventAction: eventAction,
            category: 'Content',
            label: url
        );
      }`
      
      here, 
      widget.guideline!.children!.getNameForChapterNumber(widget.pageSession)! return a string, eg Pulmonary Hear Disease
      url is any standard url as you can see in attached screenshot (the urls too are getting encoded)
      
      function definition for sending events:
 
` Future<void> sendEventsToGoogleAnalyticsLegacy({
    String? eventAction,
    String? category,
    String? label,
    Map<String?, dynamic>? params
  }) async {
    if (isAnalyticsEnabled()) {
      final ga = await GoogleAnalytics.instance;
      final tracker = await ga.newTracker('My-UA-id');
      final event = EventBuilder();
      event.category = category;
      event.action = eventAction;
      if(label != null){
        event.label = label;
      }
      await tracker.send(event);
    }
  }`

**Comment by miroslavbaudys** [comment]
Thanks

**Comment by Ashish6295** [comment]
I can see that in the helper method of the package (i've attached code below)

`class Helper {
  static String encodeValue(final String value) {
    if (Platform.isIOS) {
      return Uri.encodeComponent(value);
    }
    return value;
  }

  static String? convertBool(final bool? value) {
    if (value != null) {
      return value ? "1" : "0";
    }
    return null;
  }
}`


you've added encoding for iOS, this causing the weird encoding of string as attached in my screen shot
what is the purpose of doing that, please make it named parameter which i can set to true or false when i access the tracker.send method in my code

**Comment by miroslavbaudys** [comment]
Very good point, I guess there was some problem with underlaying GA SDK that did not accept value without encoding. Can you test it without that condition if it works? I will do my test later today and prepare fix.

**Comment by Ashish6295** [comment]
yes, actually i've removed encoding part from the code
and it worked for me

i've fired some urls too and i'll get the logs in system by tomorrow

but you may add a named boolean parameter accessible for our code 
those who need the encoding will keep it and some like will not use it

**Comment by miroslavbaudys** [comment]
Ok thanks for info. I will test if that condition is still needed, because I updated GA SDK in previous version.

**Comment by miroslavbaudys** [comment]
Released version 1.0.4
added setValueEncoder for disable enconding value or set custom value encoder

**Comment by Ashish6295** [comment]
> Released version 1.0.4 added setValueEncoder for disable enconding value or set custom value encoder

Thank you so much will try it out now
